#!/bin/bash

SOURCE=~/alx/mybetty/myVBetty/
DESTINATION=~/alx/personal_revision/
CHK=~/alx/personal_revision/myVBetty/
SNAME="/alx/mybetty/myVBetty/"
DNAME="/personal_revision/"

echo ""
if [ -d "$CHK" ]; then
    echo "The directory $(basename $CHK) exists."
else
    echo "The directory $(basename $CHK) does not exist."
	echo "Creating $(basename $CHK)..."
	mkdir $CHK
fi

echo ""
echo -e "........Copying from $SNAME"
echo -e ".........into $DNAME"
echo ""
echo -e "NOTE: You are in $(pwd)"
echo ""
echo -e "Pls, wait..."
cp -r "$SOURCE" "$DESTINATION"

echo -e "Copied successfully."
echo -e ""
echo -e "Listing the content of the destination..."
echo -e ""

echo -e "Therefore in personal_revision/myVBetty/ ..."
echo -e "............................................"
ls -a $DESTINATION/myVBetty/
echo -e "............................................"
echo ""

echo -e "Therefore in personal_revision/myVBetty/modifications ..."
echo -e "............................................"
ls -a $DESTINATION/myVBetty/modifications
echo -e "............................................"
echo ""

echo -e "Therefore in personal_revision/myVBetty/modifications/.scpts..."
echo -e "............................................"
ls -a $DESTINATION/myVBetty/modifications/.scpts
echo -e "....................Done...................."
echo ""