#!/bin/bash

SOURCE=~/alx/custom_commands/
DESTINATION=~/alx/mybetty/myVBetty/modifications/
SNAME="/alx/custom_commands/"
DNAME="/alx/mybetty/myVBetty/modifications"
echo ""
echo -e "........Copying from $SNAME"
echo -e ".........into $DNAME"
echo ""
echo -e "NOTE: You are in $(pwd)"
echo ""
echo -e "Pls, wait..."
#cp -r "$SOURCE" "$DESTINATION"
rsync -r --exclude={.,.git,..} "$SOURCE" "$DESTINATION"
#rsync -r --exclude={.,.git,..} "$SOURCE1" "$SOURCE2" "$DESTINATION"

echo -e "Copied successfully."
echo -e ""
echo -e "Listing the content of the destination..."
echo -e ""

echo -e "Therefore in mybetty/myVBetty/modifications ..."
echo -e "............................................"
ls -a $DESTINATION
echo -e "............................................"
echo ""

echo -e "Therefore in mybetty/myVBetty/modifications/.scpts..."
echo -e "............................................"
ls -a $DESTINATION/.scpts
echo -e "....................Done...................."
echo ""