#!/usr/bin/env bash

sedFunc () {
	local VERSION="$1"
	local FILEPATH="$2"
	sed -i "s|VERSIONNUMBER=\"v\?[0-9]\{8\}\.[0-9]\{4\}\"|VERSIONNUMBER=\"$VERSION\"|g" "$FILEPATH"
}

# use find for dynamic path resolution
# custom_commands=$(find "." -type d -name custom_commands -exec test -d "{}/.git" \; -print)

# use absolute path for clarity
currDir="$(pwd)"
custom_commands="$HOME/alx/custom_commands"
cd "$custom_commands"
setScript="$custom_commands/setScript.sh"
check4UpdateCustomCommands="$custom_commands/.scpts/pyfiles/check4Update"
# check4UpdateXbin="$HOME/.xbin/pyfiles/check4Update"
# echo "custom_commands: $custom_commands"
NEW_VERSION=$(date +"%Y%m%d.%H%M")

sedFunc "$NEW_VERSION" "$setScript"
sedFunc "$NEW_VERSION" "$check4UpdateCustomCommands"
# sedFunc "$NEW_VERSION" "$check4UpdateXbin"

git add "$setScript"
git add "$check4UpdateCustomCommands"
git commit -m "Auto bumped version to $NEW_VERSION"
cd "$currDir"

echo "✅ Auto bumped version to $NEW_VERSION."
