#!/usr/bin/env bash

SCPTS=".scpts/pyfiles/check4Update"
XBIN="$HOME/.xbin/pyfiles"

is_repo() {
	[[ -d ".git" ]]
}

update_script () {
	# ...update check4Update commands.................. #
	echo "custom commands" > "$XBIN/check4Update"
	cp "$SCPTS" "$XBIN/check4Update"
	chmod +x "$XBIN/check4Update"
	# pwd
}

check4UpdateFunc() {
	clear # uncomment this
	echo -e ""
	# --- SETTINGS ---
	LOCAL_FILE="./setScript.sh"
	VERSIONNUMBER="20250701.2233"
	REMOTE_FILE_URL="https://raw.githubusercontent.com/DafetiteOgaga/custom_commands/master/setScript.sh"

	# --- EXTRACT LOCAL VERSION ---
	# local_version=$(grep -oP 'VERSIONNUMBER="\K[0-9.]+' "$LOCAL_FILE")
	local_version="$VERSIONNUMBER"

	# --- EXTRACT REMOTE VERSION ---
	remote_file_content=$(curl -fsSL "$REMOTE_FILE_URL") || {
		echo "Failed to fetch remote file."
		return
	}
	# echo "remote_file_content: $remote_file_content"
	remote_version=$(echo "$remote_file_content" | grep -oP 'VERSIONNUMBER="\K[0-9.]+')

	if [[ "$local_version" != "$remote_version" ]]; then
		# echo ""
		echo "Update Available!"
		echo "------------------------------"
		echo "Current Version: $local_version"
		echo "Latest Version:  $remote_version"
		echo ""
		read -n 1 -s -r -p "Pull update? [y/N] >>> " PULL_UPDATE
		if [[ "$PULL_UPDATE" =~ [nN] ]]; then
			echo -e "no\n"
			echo -e "Skipping update..."
		else
			echo -e "yes"
			echo -e "\nPulling update...\n"
			if is_repo; then
				gitOp=$(git pull origin master 2>&1)
				if [[ "$?" -eq 0 ]]; then
					echo -e "$gitOp"
					update_script
					echo -e "\nUpdate pulled successfully."
				else
					echo -e "Git Pull Failed:\n$gitOp"
					sleep 1
				fi
			else
				echo "This is not a git repository. Cannot pull updates."
				exit 1
			fi
		fi
		sleep 1
		echo -e ""
	fi
}

# ENTRY POINT

NOW=$(date +%s)
LAST_UPDATE_FILE="$XBIN/lastUpdateTime.txt"

mkdir -p "$(dirname "$LAST_UPDATE_FILE")"

if [[ ! -f "$LAST_UPDATE_FILE" ]]; then
	echo "Last update not tracked. Starting tracker."
	echo "$NOW" > "$LAST_UPDATE_FILE"
fi

LAST_CHECK=$(cat "$LAST_UPDATE_FILE")

# echo "NOW: $NOW"
# echo "LAS: $((LAST_CHECK + 86400))"
# echo "NOW > LAST_CHECK: $(( NOW > LAST_CHECK + 86400 ))"

if (( NOW > LAST_CHECK + 86400 )); then
	# echo ""
	# echo "Last update check was more than 24 hours ago."
	# read ch
	check4UpdateFunc
	echo "$NOW" > "$LAST_UPDATE_FILE"
# else
# 	echo "Last update check was less than 24 hours ago."
# 	read ch
fi

# echo "PULL_UPDATE: $PULL_UPDATE"
# read yes
