#!/bin/bash

path1="$HOME/.xbin/pyfiles"
output=$(2>&1 python3 -m django --version)
items=$(ls)

if [[ "$output" == *"No module named django"* ]]; then
	echo ""
	echo "You don't have django installed or check your virtual environment"
	echo "pip install django"
	echo ""
elif [[ "$1" != "project" ]]; then
	if [[ -z "$1" ]]; then
		echo ""
		echo "Django version: $output"
	elif [[ "$items" != *"manage.py"* && -n "$1" ]]; then
		echo "change to the directory containing \"manage.py\""
	elif [[ "$1" == "pass" ]]; then
		database="$(python3 $path1/check_db.py 2>&1)"
		echo "$database"
		mysqlclient="$(python3 $path1/check_MySQLdb.py 2>&1)"
		# echo "$mysqlclient"
		if [[ "$mysqlclient" == *"DRF not installed"* ]]; then
			echo ""
			echo "You seem to have djangorestframework installed."
			echo "But You don't have djangorestframework installed properly."
			echo "Run: drf command"
		elif [[ "$database" == *"MySQL"* && "$mysqlclient" == *"MySQLdb not installed"* ]]; then
			echo ""
			echo "You don't have mysqlclient(django connector) installed."
			echo "pip install mysqlclient"
			echo "if any issue:"
			echo "    sudo apt-get install pkg-config"
			echo "    sudo apt-get install libmysqlclient-dev"
			echo "    pip install mysqlclient"
		fi
	fi
fi
