#!/bin/bash

USERNAME="$1"
EMAIL="$2"

echo ""
echo -e "Global Author Identity Configuration"
echo "........................................."
echo ""

echo -n "Enter your Github Username >>> "
read USERNAME

echo ""

echo -n "Enter your Github Email address >>> "
read EMAIL

echo ""

if [[ -z "$USERNAME" || -z "$EMAIL" ]]; then
	echo -e "You must supply your Username and Email to proceed"
	echo ""
	exit 1
fi

echo -e "Configuring Username: $USERNAME"
echo -e "Configuring Email: $EMAIL"
echo -e "This configuration applies globally(Default)..."
git config --global user.email "$EMAIL"
git config --global user.name "$USERNAME"
echo -e "Done...\n"
