#!/usr/bin/env bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django pass)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

path2="$path1/pyfiles"
python_command=$("$path2/isGitBash" 2>&1)
# command=$(cat $path1/pymanage)
# echo "command: $command"
command="$python_command manage.py collectstatic --noinput"
$command
