#!/usr/bin/env bash

OS=$(uname -s)
is_git_bash() {
    [[ "$OSTYPE" == "msys" || "$MSYSTEM" == MINGW* ]]
}
is_wsl() {
    grep -qi "microsoft" /proc/version 2>/dev/null
}
is_macos() {
    [[ "$OSTYPE" == "darwin"* ]]
}
is_linux() {
    [[ "$OSTYPE" == "linux-gnu"* && ! $(is_wsl) ]]
}
# echo "OS: $OS"

echo ""
echo "Wait for it..."
if is_git_bash || is_wsl; then explorer.exe .
elif is_linux; then xdg-open .
elif is_macos; then open .
fi
# if [[ -n "$WSL_DISTRO_NAME" || "$OS" == "Windows" || "$OS" == "Windows" ]]; then
#     explorer.exe .
# elif [[ "$OS" == "Linux" ]]; then
#     xdg-open .
# fi

echo -e "....................Done....................\n"
