#!/usr/bin/env bash

DBIN="$HOME/.xbin"

echo ""
echo "............All of your custom commands.................."
ls "$HOME/.xbin" | grep -v -e "^pyfiles" -e "^check4Update" -e "^pymanage" | column
echo -e "......................................................\n"