#!/usr/bin/env bash

success() {
	if [[ "$?" == 0 ]]; then
		echo "Success"
	fi
}

others() {
	for i in {1..6}; do
		install_command="npm install"
		postcss=0
		if [[ "$i" == 1 ]]; then
			app_command=" styled-components"
		elif [[ "$i" == 2 ]]; then
			app_command=" autoprefixer postcss-cli"
			postcss=1
		elif [[ "$i" == 2 ]]; then
			app_command=" react-router-dom"
		elif [[ "$i" == 3 ]]; then
			app_command=" react-player"
		elif [[ "$i" == 4 ]]; then
			app_command=" @chakra-ui/react"
		elif [[ "$i" == 5 ]]; then
			app_command=" formik"
		elif [[ "$i" == 6 ]]; then
			app_command=" yup"
		fi
		echo ""
		read -n 1 -s -r -p "Install $app_command? [y/N] >>> " install
		
		if [[ "$install" =~ [yY] ]]; then
			echo "$app_command"
			install_command+="$app_command"
			# echo "install_command #####: $install_command"
			$install_command
			if [[ "$postcss" -eq 1 ]]; then	
				src="$(2>&1 find "." -type d -name "node_modules" -prune -o -type d -name "src" -print)"
				echo -e "module.exports = {\n\tplugins: [\n\trequire('autoprefixer')\n\t]\n};" > "$src/postcss.config.js"
			fi
			success
		elif [[ "$install" =~ [nN] ]]; then
			echo "No"
			continue
		fi
	done
}

path1="$HOME/.xbin/pyfiles"
# path1="$HOME/alx/custom_commands/.scpts/pyfiles"
check="$(2>&1 $path1/nodeAndNpm dependencies)"
if [[ -n "$check" ]]; then
	echo "$check"
	if [[ "$check" == *"not install"* ]]; then
		exit 1
	fi
fi
others
