#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	else
		exit 1
	fi
fi
