#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

command="pip install djoser"

if [ "$#" -gt 0 ]; then
	echo ""
	echo "This command takes no arguments"
elif [ "$#" -eq 0 ]; then
	$command
	echo ""
	$(echo "djoser" | python3 $path1/pyfiles/configure_settings_py.py)
	echo "djoser is installed successfully and configured under INSTALLED_APPS in settings.py"
fi