#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

command=$(cat $path1/pymanage)
# echo "command: $command"
command+="shell"
$command
