#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

command="pip3 install djangorestframework"

if [ "$#" -gt 0 ]; then
	echo ""
	echo "This command takes no arguments"
elif [ "$#" -eq 0 ]; then
	path1="$path1/pyfiles/configure_settings_py.py"
	$command
	echo ""
	output1="$(echo "rest_framework" | python3 $path1 2>&1)"
	echo "$output1"
	output2="$(echo "rest_framework.authtoken" | python3 $path1 2>&1)"
	echo "$output2"
	echo "django RESTframework and its authentication token functionality installed successfully and configured under INSTALLED_APPS in settings.py"
	echo "consider using: djoser command. For easy authentcation implementation."
	echo "Note: if you are using a virtual environment, you need to specify the path to your interpreter."
fi