#!/bin/bash

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

make_exe()
{
	echo -e "\n========== $argument =========="
	jscount=$((count + 1))
	if [[ $(head -n 1 "$argument" | grep -c "#!/usr/bin/env node") -eq 0 ]]; then
		tmpfile=$(mktemp)
		echo -e "#!/usr/bin/env node\n" > "$tmpfile"
		cat "$argument" >> "$tmpfile"

		mv "$tmpfile" "$argument"
	fi
	sleep 1
	chmod +x "$argument"
	echo -e "Shebang line prepended to $argument and given the execute permission"
}

count=1
for argument in "$@" ; do
    if [[ $argument == *".sh" ]]; then
		make_exe
	else
		echo -n "Is $argument a javascript? [y/N] >>> "
		read -n 1 -s -r RES
		echo -e "$RES"
		if [[ $RES =~ [yY] ]]; then
			make_exe
		else
			nojscount=$((count + 1))
		fi
    fi
	count=$((count + 1))
done

if [[ $nojscount == $count ]]; then
echo -e ""
	echo -e "No javascript found."
fi

echo -e ""