#!/usr/bin/env bash

path1="$HOME/.xbin/pyfiles"
check=$(2>&1 $path1/django arg)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

command="pip install djangorestframework-simplejwt"

if [ "$#" -gt 0 ]; then
	echo ""
	echo "This command takes no arguments"
elif [ "$#" -eq 0 ]; then
	$command
	echo ""
	output1="$(echo "rest_framework_simplejwt" | python3 $path1/configure_settings_py.py 2>&1)"
	echo "$output1"
	echo ""
	if [[ "$output1" == *"you have a django app installed?"* ]]; then
		exit 1
	fi
	echo "..............................................."
	echo "JWT(json web token) is installed successfully and configured under INSTALLED_APPS in settings.py and in urls.py"
	echo "Goto settings.py and uncomment some settings under DJOSER and REST_FRAMEWORK variables"
	echo ""
	echo -e "installed API endpoints:
\t - /token/		generates a token for registered users
\t - /token/refresh/	refreshes token"

fi