#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

command=$(cat $path1/pymanage)
command+="makemigrations"

if [ "$#" = "0" ]; then
	$command
elif [ "$#" -gt 0 ]; then
	for argument in "$@" ; do
		command+=" $argument"
	done
	$command
fi
