#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django pass)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	fi
fi

echo ""
command=$(cat $path1/pymanage)
command+="makemigrations"

if [ "$#" = "0" ]; then
	$command
elif [ "$#" -gt 0 ]; then
	for argument in "$@" ; do
		command+=" $argument"
	done
	$command
fi
