#!/usr/bin/env bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django pass)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

echo ""
# command=$(cat $path1/pymanage)
path2="$path1/pyfiles"
python_command=$("$path2/isGitBash" 2>&1)
command="$python_command manage.py makemigrations"

if [ "$#" = "0" ]; then
	$command
elif [ "$#" -gt 0 ]; then
	for argument in "$@" ; do
		command+=" $argument"
	done
	$command
fi
