#!/usr/bin/env python3

import subprocess, sys
from pyfiles.django_codes import output_func, error_check, error_response

code, response = error_check()
stop = error_response(code, response)
if stop:
    sys.exit(stop)

if len(sys.argv) > 2:
	args = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
	sys.argv = args
if len(sys.argv) == 2:
	sys.argv[1] = 'migration'
command = output_func()
print()
subprocess.run(command.split())
