#!/bin/bash

path1="$HOME/.xbin/pyfiles"
check=$(2>&1 $path1/django pass)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

if [[ "$#" -gt 0 ]]; then
	echo ""
	echo "Invalid Entry!"
	exit 1
fi

command1="makemigrations"
$command1

command2="migrate"
$command2
