#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django pass)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	fi
fi

if [[ "$#" -gt 0 ]]; then
	echo ""
	echo "Invalid Entry!"
	exit 1
fi

command1="makemigrations"
$command1

command2="migrate"
$command2
