#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

if [[ "$#" -gt 0 ]]; then
	echo ""
	echo "Invalid Entry!"
	exit 1
fi

command1="makemigrations"
$command1

command2="migrate"
$command2
