#!/usr/bin/env bash

path1="$HOME/.xbin"
# path1="$HOME/alx/raw/cfiles"
check=$($path1/pyfiles/mongo arg 2>&1)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

echo "MongoDB server operations ..."
echo "1. Start"
echo "2. Stop"
echo "3. Restart"
echo "4. Check server status"
echo "[q] to quit"
echo -e "\nUse 'mongosh' command - to start the MongoDB shell\n"
echo ""
read -n 1 -s -r -p "Select an option >>> " MONGO_OPTION
if [[ "$MONGO_OPTION" =~ [qQ] ]]; then
	echo "$MONGO_OPTION"
	echo ""
	echo "Cheers"
	exit 0
elif [[ "$MONGO_OPTION" =~ [1] ]]; then
	echo "Starting server ..."
	sudo systemctl start mongod
	echo "MongoDB started successfully."
elif [[ "$MONGO_OPTION" =~ [2] ]]; then
	echo "Stopping server ..."
	sudo systemctl stop mongod
	echo "MongoDB stopped successfully."
elif [[ "$MONGO_OPTION" =~ [3] ]]; then
	echo "Restarting server ..."
	sudo systemctl restart mongod
	echo "MongoDB restarted successfully."
elif [[ "$MONGO_OPTION" =~ [4] ]]; then
	echo "Checking server status ..."
	sudo systemctl status mongod
else
	echo "Invalid option selected. Please try again."
	exit 1
fi
