#!/usr/bin/env bash

path1="$HOME/.xbin"
# path1="$HOME/alx/raw/cfiles"
check=$($path1/pyfiles/mysql arg 2>&1)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

command="sudo service mysql start"
$command
echo ""
echo "Started MySQL Server."

# sudo mysql_secure_installation
# sudo apt install mysql-client