#!/usr/bin/env python3

from pyfiles.git_codes import add_commit_all, pull, push
import os

user_list = [(os.listdir())[i] for i in range(1, len(os.listdir()))]
add_commit_all()
pull()
push(user_list)
