#!/usr/bin/env bash

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

has3=$("./pyfiles/isGitBash" 2>&1)
for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    python$has3 -m compileall -b "$argument"
    echo -e "Done."
done
