#!/usr/bin/env bash

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

path2="$HOME/.xbin/pyfiles"
python_command=$("$path2/isGitBash" 2>&1)
for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    "$python_command -m compileall -b $argument"
    echo -e "Done."
done
