#!/usr/bin/env bash

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    pycodestyle --show-source "$argument"
done
