#!/usr/bin/env bash

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

path2="$HOME/.xbin/pyfiles"
python_command=$("$path2/isGitBash" 2>&1)
headline="#!/usr/bin/env $python_command"
make_exe()
{
	echo -e "\n========== $argument =========="
	pycount=$((count + 1))
	if [[ $(head -n 1 "$argument" | grep -c "$headline") -eq 0 ]]; then
		tmpfile=$(mktemp)
		echo -e "$headline\n" > "$tmpfile"
		cat "$argument" >> "$tmpfile"

		mv "$tmpfile" "$argument"
	fi
	sleep 1
	chmod +x "$argument"
	echo -e "$argument is now executable."
}

count=1
for argument in "$@" ; do
    if [[ $argument == *".py" ]]; then
		make_exe
	else
		echo -n "Is $argument a python file? [y/N] >>> "
		read -n 1 -s -r RES
		echo -e "$RES"
		if [[ $RES =~ [yY] ]]; then
			make_exe
		else
			nopycount=$((count + 1))
		fi
    fi
	count=$((count + 1))
done

if [[ "$nopycount" == "$count" ]]; then
echo -e ""
	echo -e "No python file found."
fi

echo -e ""