#!/usr/bin/env bash

operation_entries()
{
    local args=("$@")
    echo ""
    for argument in "${args[@]}"; do
        git restore "$argument"
        echo "$argument restored to the same state as last commit ..."
    done
}

RESP="$1"
if [[ -n "$RESP" ]]; then
    operation_entries "$@"
else
    read -rp "Enter the path to file/directory name(s). [q] - quit >>> " -a ARGS
    if [[ "${ARGS[0]}" =~ ^[qQ]$ ]]; then
        echo -e "\nCheers."
        exit 0
    fi
    operation_entries "${ARGS[@]}"
fi
