#!/usr/bin/env python3

import subprocess, sys, os
from pyfiles.django_codes import output_func, error_check, main, error_response

code, response = error_check()
stop = error_response(code, response)
if stop:
    sys.exit(stop)

if len(sys.argv) == 2 and type(sys.argv[1]) != int and len(sys.argv[1]) != 4:
    print()
    print('port number must be an integer of 4 numbers')
    print()
    sys.exit(1)

text_path = os.getcwd()
print()
command1 = main(runserver='yes')

os.chdir(command1)

command2 = output_func(text_path=text_path)

try:
    ctrl_c = subprocess.run(command2.split())
except KeyboardInterrupt:
    print()
    print('Development Server exited.')
    print()
