#!/usr/bin/env python3

import subprocess, sys
from pyfiles.django_codes import output_func, error_check, error_response

error_check()
code, response = error_check()
# print('error code 12abcd: ', code, 'response 12abcd: ', response)
stop = error_response(code, response)
if stop:
    sys.exit(stop)

if len(sys.argv) > 2:
	args = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
	sys.argv = args
if len(sys.argv) == 2:
	sys.argv[1] = 'show'
command = output_func()
print()
subprocess.run(command.split())
