#!/usr/bin/env python3

import sys, os
from pyfiles.git_codes import diff

args = sys.argv[1:]
one_arg = len(args) > 1
if one_arg:
	print('Usage: showDiff [file]')
	sys.exit(1)

if len(args) == 1:
	file = args[0]
	if not os.path.exists(file):
		print(f'File {file}: Not found in directory.')
		print('Change into the directory where the file is located\nor provide the full path to the file.')
		sys.exit(1)
	if not os.path.isfile(file):
		print(f'{file} is not a file.')
		sys.exit(1)
	diff(file=file)
else:
	diff()
