#!/usr/bin/env python3

import subprocess, sys
from pyfiles.django_codes import *

error_check()
code, response = error_check()
stop = error_response(code, response)
if stop:
	sys.exit(stop)

if len(sys.argv) > 1:
	args = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
	sys.argv = args
sys.argv = sys.argv + ['show']
command = output_func()
print()
check_database_type()
output = subprocess.run(command.split(), capture_output=True, text=True)
if output.stderr:
	moduleNotFound_in_settings(output.stderr)
if output.stdout:
	print('output.stdout:', output.stdout)
