#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django project)
if [[ -n "$check" && "$check" != "fixed" ]]; then
	echo "$check"
	echo ""
	exit 1
fi

command="django-admin"
command+=" startproject"

if [ "$#" != "1" ]; then
	echo ""
	echo "Enter a project name as argument"
elif [ "$#" -eq 1 ]; then
	# echo "Project name: $1"
	command+=" $1"
	$command
fi