#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [ -n "$check" ]; then
	echo "$check"
	echo ""
	exit 1
fi

command=$(cat $path1/pymanage)
command+="startapp"

if [ "$#" != "1" ]; then
	echo ""
	echo "Enter an app name as argument"
elif [ "$#" -eq 1 ]; then
	# echo "App name: $1"
	command+=" $1"
	$command
fi