#!/bin/bash

path1="$HOME/.xbin/pyfiles"
check=$(2>&1 $path1/django project)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

command="django-admin"
command+=" startproject"

if [ "$#" != "1" ]; then
	echo ""
	echo "Enter a project name as argument"
elif [ "$#" -eq 1 ]; then
	# echo "Project name: $1"
	command+=" $1"
	$command
	echo ""
	pip install django-extensions
	echo ""
	output1="$(echo "django_extensions" | python3 $path1/configure_settings_py.py 2>&1)"
	echo "$output1"
	echo "Install djangoUrls command and start checking all your configured urls"
fi