#!/usr/bin/env bash

path1="$HOME/.xbin/pyfiles"
check=$(2>&1 $path1/django project)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"*
		|| "$check" == *"Multiple databases"* || "$check" == *"Unknown database"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient"* ||
			"$check" == *"You don't have djangorestframework"* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"You don't have django installed"* ]]; then
		echo ""
		read -n 1 -s -r -p "Install django? [y/N] >>> " INSTALL_DJANGO
		if [[ "$INSTALL_DJANGO" =~ [yY] ]]; then
			echo ""
			echo "Installing django..."
			pip install django
			echo "exit result: $?"
			if [[ $? -eq 0 ]]; then
				echo "Django installed successfully."
			else
				echo "Failed to install django. Please check your pip configuration."
			fi
		else
			echo ""
			echo "Django installation skipped."
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

python_command=$("$path1/isGitBash" 2>&1)
command="django-admin"
command+=" startproject"

if [ "$#" != "1" ]; then
	echo ""
	echo "Enter a project name as argument"
elif [ "$#" -eq 1 ]; then
	# echo "Project name: $1"
	command+=" $1"
	$command
	echo ""
	sleep 3
	pip install -q django-extensions
	echo ""
	output1="$(echo "django_extensions" | "$python_command" "$path1/configure_settings_py.py" 2>&1)"
	echo "$output1"
	echo "Install djangoUrls command and start checking all your configured urls"
fi