#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	fi
fi

command=$(cat $path1/pymanage)
command+="startapp"

if [ "$#" != "1" ]; then
	echo ""
	echo "Enter an app name as argument"
elif [ "$#" -eq 1 ]; then
	# echo "App name: $1"
	command+=" $1"
	$command
	output="$(echo "$1" | python3 $path1/pyfiles/configure_settings_py.py 2>&1)"
	echo "$output"
	echo "$1 app created successfully and configured under INSTALLED_APPS in settings.py"
fi