#!/bin/bash

path1="$HOME/.xbin"
check=$(2>&1 $path1/pyfiles/django arg)
if [[ -n "$check" ]]; then
	echo ""
	echo "$check"
	if [[ "$check" == *"SQLite"* || "$check" == *"MySQL"* || "$check" == *"PostgreSQL"* ]]; then
		if [[ "$check" == *"You don't have mysqlclient(django connector) installed."* ]]; then
			exit 1
		fi
	elif [[ "$check" == *"change to the directory containing"* || "$check" == *"You don't have django installed or"* ]]; then
		exit 1
	fi
fi

if [ "$#" -gt 0 ]; then
	echo ""
	echo "This command takes no arguments"
elif [ "$#" -eq 0 ]; then
	path1="$path1/pyfiles/configure_settings_py.py"
	echo ""
	# $(echo "static" | python3 $path1)
	output="$(echo "static" | python3 $path1 2>&1)"
	echo "$output"
	echo "STATIC DIRS has been installed and configured in project and settings.py"
fi