#!/usr/bin/env bash

OS=$(uname -s)
is_git_bash() {
    [[ "$OSTYPE" == "msys" || "$MSYSTEM" == MINGW* ]]
}
is_wsl() {
    grep -qi "microsoft" /proc/version 2>/dev/null
}
is_macos() {
    [[ "$OSTYPE" == "darwin"* ]]
}
is_linux() {
    [[ "$OSTYPE" == "linux-gnu"* && ! $(is_wsl) ]]
}

XBIN_DIR="$HOME/.xbin"

echo ""
echo "Wait for it..."
if is_git_bash || is_wsl; then explorer.exe "$XBIN_DIR"
elif is_linux; then xdg-open "$XBIN_DIR"
elif is_macos; then open "$XBIN_DIR"
fi
# if [[ -n "$WSL_DISTRO_NAME" || "$OS" == "Windows" ]]; then
#     explorer.exe "$HOME/.xbin"
# elif [[ "$OS" == "Linux" ]]; then
#     xdg-open "$HOME/.xbin"
# fi

echo -e "....................Done....................\n"
